### ISSUE TITLE
Be more expressive about a Version Matrix

### ISSUE THREAD

**Issue by MeFisto94** [stephengold/Minie#21]
When updating the dependencies for the SDK, I had troubles to find out which version of Minie is the last one targetting 3.4.0.
I've found the docs page and somewhere down it said "`4.6.1` does not support 3.4.0 anymore", so I could deduct that I need 4.6.0.
From there, I've followed the POMs to add Heart 7.1.0 and Wes 0.6.7 (that needs Heart 7.0, but Wes 0.6.8 would need Heart 7.2).

Maybe you can add some easy to spot table or any other form of documentation, so one can easily see what versions they need when targetting a specific jme version (in case they can't bump their game's version)

**Comment by stephengold** [comment]
Thanks for pointing this out. Is there some reason you don't want to use the latest Engine release?

**Comment by MeFisto94** [comment]
In this case because I'm crafting the SDK 3.4 release, but otherwise I can certainly see a project being in phases where they don't want to upgrade but instead work on things first.
jME isn't really breaking when changing the version, typically, but I can still see some workflow of rather being safe than sorry and upgrading later.

**Comment by stephengold** [comment]
@MeFisto94: I agree the docs could be more helpful.

I guess there are 2 parts to this issue:
 + Be explicit about what version of Minie to use with each release of the Engine.
 + Document what versions of SimMath and Heart are used by each version of Minie.

I think I wrote the docs the way I did because (for various reasons) I wanted to nudge people toward recent versions of the Engine. I'm still thinking about how best to support users of old Engine versions.

Of course, another way of nudging people toward recent versions of the Engine is to provide SDKs for those versions. So I'm glad you're working on SDK 3.4. If I published a "Minie-4.8.0+for34" release specifically for SDK 3.4, would you use it? Which version of the Engine should it target: 3.4.0-stable or 3.4.1-stable?

**Comment by stephengold** [comment]
I added a new documentation page with a table of releases: https://stephengold.github.io/Minie/minie/depends.html

@MeFisto94: Let me know whether the new page solve this issue.

**Comment by MeFisto94** [comment]
That solves it, yeah. I can use the `Minie-4.8.0+for34` on the SDK. I guess targetting 3.4.1-stable would make more sense, as the only 3.4 release, unless you have already targetted 3.4.0, but I guess we have that flexibility inside the versions anyway.

The way that page is written, you only need to ensure, that Heart and sim-math are compatible with the jme version that Minie uses, but I guess that's a thing you need to do anyway.

I'll keep the issue open because of the SDK's Upgrade of the Minie version, but then it can be closed
