### ISSUE TITLE
Minie doesn't work with jMonkeyEngine SDK v3.3.0-stable on Windows 10

### ISSUE THREAD

**Issue by tdhargraves** [stephengold/Minie#24]
The fix is to use Gradle 6.7, not 7.4 as used by Minie. Details follow:

Running jMonkeyEngine SDK v3.3.0-stable on Windows 10.
Downloaded Minie-4.8.0-source from website, and via gradle.
Minie built OK.
Opened Minie-4.8.0 projects in SDK, they appeared as Gradle Builds..
Got the following error for all subprojects, and the subprojects wouldn't open:

groovy.lang.MissingPropertyException: Could not get unknown property 'compileConfigurationName' for source set 'main' of type org.gradle.api.internal.tasks.DefaultSourceSet.

Researched using google, found a problem reported with Netbeans and gradle:

https://stackoverflow.com/questions/67635885/spring-initializr-gradle-project-fails-unknown-property-compileconfigurationnam
Which identified a known problem: "Gradle 7.0 is not supported in NetBeans 12.3".

I've no idea what version of netbeans the JME SDK uses, but Minie uses gradle v7.4.

Fix:
Installed gradle-6.7 on my PC
cd into the Minie build: cd Minie\gradle\wrapper
Enter command: .\gradle wrapper
This updated the version of gradle in Minie.
The wrapper changed to gradle-6.7.

Re-Opened Minie-4.8.0 projects in the SDK.
Minie project built OK, and the SDK errors had gone.
Some examples ran OK.

**Comment by stephengold** [comment]
Thank you for documenting this issue. However, I see it as an issue with the JMonkeyEngine SDK and NetBeans, not an issue with Minie.

The build instructions for Minie say to use the command line, not the SDK.

It would be nice if one could build Minie in the SDK. However, downgrading the Gradle wrapper to v6.7 is not a good solution. If I do so, won't someone try to build with an even older SDK that doesn't support Gradle at all?

**Comment by tdhargraves** [comment]
I agree Stephen, 

it is an SDK issue, but going back to Gradle 6.7 does make it all work. For now… 😊

As reported by others, a later version of Netbeans works, but introduces more bugs 😲

 

Out of interest, what is your development environment?

I have always liked an SDK myself, and got along fine with the JME SDK, but I am open to change!

 

I was enjoying reading your new code. Much more logical and readable.

But could you please tell be why Torso bones are treated separately?

 

Thanks,

Tom.

**Comment by stephengold** [comment]
I'm glad you agree this is an SDK bug, not a Minie bug.
I'm glad to have a documented workaround, in case someone else encounters the same issue.
I'm going to close this issue now. 

Up until February 2022, I was still using v3.2.4 of the JMonkeyEngine SDK. I tried the v3.3 SDK and IDEA, but found the transitions difficult. Currently I do most of my software development in NetBeans v12.6, and I'm preparing to upgrade to NetBeans v13.

In `DynamicAnimControl`, torso bones are handled specially because they directly update the C-G model's position (in dynamic mode) or are directly updated by it (in kinematic mode).

Feel free to continue this discussion at the Forum or via e-mail.
